import { IConstantsTheme } from './interfaces'

export default {
  light: {
    _key: 'Theme',
    BACKGROUNDCOLOR_LG: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR_LG_Disabled: ['#efefef', '#cccccc', '#efefef'],
    BACKGROUNDCOLOR: '#cccccc',
    BACKGROUNDCOLOR_HEADER: '#efefef',
    BACKGROUNDCOLOR_TILES: '#efefef',
    NO_ACTIVE: '#cccccc',
    TEXT_COLOR: 'black',
    ITEM_COLOR: 'black',
    CHECK_COLOR: '#15a522',
    DANGER_COLOR: '#d81b60',
    nameTheme: 'LIGHT_THEME',
    bookedColor: 'rgba(192, 159, 106, 1)',
    borderColor: '#15a522',
    borderColor2: '#414141',
    borderColorRGBA2: 'rgba(21, 165, 34, 0.3)',
    borderColorRGBA: 'rgba(21, 165, 34, 0.3)',
    favoritesCat: [
      require('../assets/icons/favoritesMixes_lt.png'),
      require('../assets/icons/favoritesBookedSounds_lt.png'),
      require('../assets/icons/favoritesBookedMusics_lt.png'),
    ],
    toFavoritesScreen: require('../assets/icons/toFavoritesScreen_lt.png'),
  },
  dark: {
    _key: 'Theme',
    BACKGROUNDCOLOR_LG: ['#3b555d', '#233237', '#204d48', '#233237', '#3b555d'],
    BACKGROUNDCOLOR_LG_Disabled: ['#104E8B', '#4A708B', '#104E8B'],
    BACKGROUNDCOLOR: '#233237',
    BACKGROUNDCOLOR_HEADER: '#233237',
    BACKGROUNDCOLOR_TILES: '#3b555d',
    NO_ACTIVE: '#146185',
    TEXT_COLOR: 'white',
    ITEM_COLOR: 'white',
    CHECK_COLOR: '#15a522',
    DANGER_COLOR: '#d81b60',
    nameTheme: 'MAIN_THEME',
    bookedColor: 'rgba(192, 159, 106, 1)',
    borderColor: 'yellow',
    borderColor2: '#414141',
    borderColorRGBA2: 'rgba(21, 165, 34, 0.3)',
    borderColorRGBA: 'rgba(255, 255, 0, 0.3)',
    favoritesCat: [
      require('../assets/icons/favoritesMixes.png'),
      require('../assets/icons/favoritesBookedSounds.png'),
      require('../assets/icons/favoritesBookedMusics.png'),
    ],
    toFavoritesScreen: require('../assets/icons/toFavoritesScreen.png'),
  },
  theme: {
    _key: 'Theme',
  },
  currentTheme: 'MAIN_THEME',
  MAIN_BACKGROUNDSTYLES: {
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title_20b: { fontSize: 20, fontWeight: 'bold', fontFamily: 'open-bold' },
  title_16b: { fontSize: 16, fontWeight: 'bold', fontFamily: 'open-bold' },
  title_14: { fontSize: 14, fontFamily: 'open-regular' },
  title_30b: { fontSize: 30, fontWeight: 'bold', fontFamily: 'open-bold' },
  text_16: { fontSize: 16, fontFamily: 'open-regular' },
  text_14b: { fontSize: 14, fontWeight: 'bold', fontFamily: 'open-bold' },
  text_12: { fontSize: 12, fontFamily: 'open-regular' },
  text_14: { fontSize: 14, fontFamily: 'open-regular' },
  text_30: { fontSize: 30, fontFamily: 'open-regular' },
  SHADOW_FOR_IOS: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
  },
} as IConstantsTheme
