export const api = {
  Registration: '/users/registration',
  SetAnonymousUser: '/users/setAnonymousUser',
  ResetPassword: '/users/resetPassword',
  ChangePassword: '/users/changePassword',
  Login: '/users/login',
  Check: '/users/check',
  GetUsers: '/users/getUsers',
  GET_DATA_SOUNDS: '/data/getFullSoundsData',
  GET_DATA_MUSICS: '/data/getFullMusicsData',
  GET_DATA_SOUNDCATEGORIES: '/data/getFullSoundCategories',
  GET_DATA_MUSICCATEGORIES: '/data/getFullMusicCategories',
  GET_DATA_NOTIFICATIONS: '/notifications/getAllNotifications',
  GET_DATA_REQUESTS: '/requests/getAllRequests',
  GET_DATA_MESSAGES: '/messages/getAllMessages',
  GET_DATA_USERS: '/users/getUsers',
  GET_DATA_ROLES: '/users/getRoles',
  ADD_NOTIFICATION: '/notifications/addNotification',
  ADD_REQUEST: '/requests/addRequest',
  GET_LISTFILE: '/files/getListFiles',
  GET_FILE: '/files/getFile',
  CREATE_FOLDER: '/files/createFolder',
  CHECK_SERVER: '/server/checkServer',
  FIND_USER_DATA: '/users/findUserData',
  UPDATE_SOUND_STATUS_NEW: '/users/updateStatusSound',
  UPDATE_MUSIC_STATUS_NEW: '/users/updateStatusMusic',
}
