export { ErrorPage as Error } from './Error/Error'
export { AppLoading } from './AppLoading/AppLoading'
export { Info } from './Info/Info'
export { Categories } from './Categories/Categories'
export { Auth } from './Auth/Auth'
